# -*- coding: utf-8 -*-
"""Cifra_de_Vigenere.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yys206llBCzcL-rM_SrfxhpeQXpHSPZZ
"""

alfabeto = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 ,;._#*"-+'


def validar_caracteres(texto):
    resultado = True
    for letra in texto:
        if letra not in alfabeto:
            resultado = False
            break
    return resultado

def validar_chave(chave, texto):
    if len(chave)< len(texto):
        return (chave * (len(texto) // len(chave) + 1))[:len(texto)]
    elif(len(chave)>len(texto)):
        return (chave[:len(texto)])
    else:
        return chave


def encriptar(textoClaro,chave):
  if(validar_caracteres(textoClaro) and validar_caracteres(chave)):
    chave_valida = validar_chave(chave, textoClaro)
    textoCifrado = ''
    for i in range(len(textoClaro)):
      textoCifrado += alfabeto[((alfabeto.find(textoClaro[i])+(alfabeto.find(chave_valida[i]))) % len(alfabeto))]
    print(f'Texto cifrado(ignore os "[]"): [{textoCifrado}]\n')
  else:
      print("Caracteres inválidos")

def desencriptar(textoCifrado,chave):
  if(validar_caracteres(textoCifrado) and validar_caracteres(chave)):
    chave_valida = validar_chave(chave, textoCifrado)
    textoClaro = ''
    for i in range(len(textoCifrado)):
      textoClaro += alfabeto[((alfabeto.find(textoCifrado[i])-(alfabeto.find(chave_valida[i]))) % len(alfabeto))]
    print(f'Texto decifrado(ignore os "[]"): [{textoClaro}]\n]')
  else:
    print("Caracteres inválidos")


def main():
  while True:
    operacao = input("Digite 1 se deseja cifrar,digite 2 para decifrar ou digite 3 para sair: ")
    if(operacao == '3'):
      break
    elif(operacao != '1' and operacao != '2'):
        print('Operacao invalida!!!')
        continue

    while True:
      texto = input(f"Digite o texto a ser {'cifrado' if operacao == '1' else 'decifrado'}: ")
      if(not validar_caracteres(texto)):
        print("Texto com caracteres inválidos!")
      else:
        break

    while True:
      chave = input("Digite a chave: ")
      if(not validar_caracteres(chave)):
        print("Chave com caracteres inválidos!")
      else :
        break

    if(operacao == '1'):
       encriptar(texto,chave)
    elif(operacao == '2'):
      desencriptar(texto,chave)
    else:
      print("Operação inválida")

main()